clang++ -std=c++11 -O3 -lsfml-audio -lsfml-window -lsfml-graphics -lsfml-network -lsfml-system -o crank \
                                \
    Animation.cpp               \
    Application.cpp             \
    Button.cpp                  \
    BloomEffect.cpp             \
    Command.cpp                 \
    CommandQueue.cpp            \
    Component.cpp               \
    Container.cpp               \
    DataTables.cpp              \
    EmitterNode.cpp             \
    Entity.cpp                  \
    GameOverState.cpp           \
    GameServer.cpp              \
    GameState.cpp               \
    KeyBinding.cpp              \
    Label.cpp                   \
    LoadingState.cpp            \
    MenuState.cpp               \
    MultiplayerGameState.cpp    \
    MusicPlayer.cpp             \
    NetworkNode.cpp             \
    ParallelTask.cpp            \
    ParticleNode.cpp            \
    PauseState.cpp              \
    Pickup.cpp                  \
    Player.cpp                  \
    PostEffect.cpp              \
    Projectile.cpp              \
    SceneNode.cpp               \
    SettingsState.cpp           \
    SoundNode.cpp               \
    SoundPlayer.cpp             \
    SpriteNode.cpp              \
    TextNode.cpp                \
    State.cpp                   \
    StateStack.cpp              \
    TitleState.cpp              \
    Ship.cpp                    \
    Utility.cpp                 \
    World.cpp                   \
    main.cpp
